### ISSUE TITLE
Fix properties for hibernate 4.3.x

### ISSUE THREAD

**Issue by mihaicostin** [mihaicostin/hibernate-l2-memcached#13]
https://github.com/mihaicostin/hibernate-l2-memcached/pull/11#issuecomment-305729078

**Comment by mihaicostin** [comment]
@yvesf can you give version 4.3.11.0 a try ?

**Comment by yvesf** [comment]
Hi @mihaicostin 
I confirm it's seems to work correctly for me.
Thank you!
