### ISSUE TITLE
Expected static method org.hibernate.cache.internal.DefaultCacheKeysFactory.createEntityKey

### ISSUE THREAD

**Issue by Ezward** [mihaicostin/hibernate-l2-memcached#14]
SpringBoot 1.5.2.RELEASE
Hibernate 5.0.1.2
hibernate-l2.memcached 5.0.1.0

I get "Expected static method org.hibernate.cache.internal.DefaultCacheKeysFactory.createEntityKey".

This seems very similar to this issue that has been closed; https://github.com/mihaicostin/hibernate-l2-memcached/issues/8

I'm using SpringBoot's included Hibernate dependancy.

**Comment by Ezward** [comment]
I retract the bug.  My version of hibernate is 5.0.12, not 5.0.1

**Comment by mihaicostin** [comment]
And is everything working ok with 5.0.12, @Ezward ?
