### ISSUE TITLE
Build for Hibernate 5.0.12.0

### ISSUE THREAD

**Issue by jederfreitas** [mihaicostin/hibernate-l2-memcached#15]
Hi,

I've been checking that the last build available on MVN Central  (5.0.1.0) it'is not compatible with Hibernate 5.0.12.0, could you please send the build of branch hibernate-5.0.1 that is already updated to Hibernate 5.0.12.0 to the central?

**Comment by mihaicostin** [comment]
Thank you for pointing that out. I've just released the artifacts to maven central. 
It might take a bit of time until they are visible. 
Let me know if you run into any issues.

**Comment by jederfreitas** [comment]
Hi, thank you for the return, it's not available yet on Maven Central.

**Comment by mihaicostin** [comment]
Hi @jederfreitas . Maybe it takes longer than usual to update (I usually recall about 1-2 hours)...
In any case, I've just made a search on maven central and at least for me it show up:

https://search.maven.org/#artifactdetails%7Ccom.github.mihaicostin%7Chibernate-l2-memcached%7C5.0.12.0%7Cjar

You should be able to use it as 
```
<dependency>
    <groupId>com.github.mihaicostin</groupId>
    <artifactId>hibernate-l2-memcached</artifactId>
    <version>5.0.12.0</version>
</dependency>
```
