### ISSUE TITLE
NonStrictReadWriteMemcachedCollectionRegionAccessStrategy.get(SharedSessionContractImplementor, Object, long) returns null 

### ISSUE THREAD

**Issue by dfsabugal** [mihaicostin/hibernate-l2-memcached#16]
In latest version we have `NonStrictReadWriteMemcachedCollectionRegionAccessStrategy` class that implements `Object get(SharedSessionContractImplementor session, Object key, long txTimestamp) throws CacheException;` method from 'RegionAccessStrategy' but actually returns `null`. This change was introduced as part of commit [b251ea4309f437038de032385e04457ef553d31c](https://github.com/mihaicostin/hibernate-l2-memcached/commit/b251ea4309f437038de032385e04457ef553d31c#diff-7f4bdce81aafc72d6feb9477366bcf29).

This makes cached entities with eagerly fetched collections that use `CacheConcurrencyStrategy.NONSTRICT_READ_WRITE` to get reloaded again from database when they are actually cached.

**Comment by mihaicostin** [comment]
Good catch @dfsabugal . 
`return null;`  doesn't look too good in there. it should be a `return region().get(key);`
I'll release a new version with the fix soon.

**Comment by mihaicostin** [comment]
hibernate-l2-memcached:5.2.17.0 should be available from maven central shortly.
It includes this fix along with a small upgrade to hibernate core to 5.2.17.0
