### ISSUE TITLE
Hibernate 5.3.x support

### ISSUE THREAD

**Issue by garethpowell** [mihaicostin/hibernate-l2-memcached#17]
Hi, 

Do you have plans to support Hibernate 5.3.x and if so when can we expect that support to be available? We currently use hibernate-l2-memcached with Hibernate 5.2.x and an Elasticache backend in AWS and are unable to upgrade to Hibernate 5.3.x without a hibernate-l2-memcached to support it. I appreciate that is probably no trivial matter following the significant changes in the caching SPI that came in Hibernate 5.3.

Best regards,
Gareth

**Comment by mihaicostin** [comment]
Hi @garethpowell . yep,  I've started looking into this but unfortunately I did not have yet the required time to make significant progress :(
In the meantime, an alternative *might* be using hibernate-jcache along with a JCache implementation / wrapper for memcached - although I did not try this myself.

**Comment by sinay90** [comment]
Hi @mihaicostin, any updates on Hibernate 5.3 and 5.4 support? 

Thanks!

**Comment by mihaicostin** [comment]
I've managed to release version 5.4.2.0 that should work with both 5.3.x (5.3.3 - 5.3.9) and 5.4.x
Please give it a try and let me know if you run into any issues.
