### ISSUE TITLE
StrategySelectionException: Unable to resolve name [com.mc.hibernate.memcached.MemcachedRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]

### ISSUE THREAD

**Issue by gandhrekunal** [mihaicostin/hibernate-l2-memcached#5]
I am trying to integrate this with Spring + Hibernate

Please help

`<beans:prop key="hibernate.cache.use_query_cache">true</beans:prop>
                <beans:prop key="hibernate.cache.use_second_level_cache">true</beans:prop>
                <beans:prop key="hibernate.cache.use_structured_entries">true</beans:prop>
                <beans:prop key="hibernate.cache.configurationResourceName"></beans:prop>
                <beans:prop key="hibernate.generate_statistics">true</beans:prop>           
                <beans:prop key="hibernate.memcached.operationTimeout">60000</beans:prop>
                <beans:prop key="hibernate.memcached.connectionFactory">KetamaConnectionFactory</beans:prop>
                <beans:prop key="hibernate.memcached.hashAlgorithm">HashAlgorithm.FNV1_64_HASH</beans:prop>
                <beans:prop key="hibernate.memcached.REGION.cacheTimeSeconds">86400000</beans:prop>
                <beans:prop key="hibernate.memcached.servers">localhost:11211</beans:prop>
                <beans:prop key="hibernate.memcached.cacheTimeSeconds">86400000</beans:prop>
                <beans:prop key="hibernate.memcached.clearSupported">false</beans:prop>
                <beans:prop key="hibernate.cache.region.factory_class">com.mc.hibernate.memcached.MemcachedRegionFactory</beans:prop>`

**Comment by mihaicostin** [comment]
Hi @gandhrekunal, can you please tell me what version of spring, hibernate and hibernate-l2-memcached are you using ? 

BTW, you can find a really simple sample integration project here: 
https://github.com/mihaicostin/samples/tree/master/java-persistence/spring-jpa-hibernate-l2cache  (hibernate 4.3 with hibernate-l2-memcached 1.1.0)

**Comment by gandhrekunal** [comment]
@mihaicostin Thanks, First I will check above  sample integration project and will let you know.
